-- 코드를 입력하세요
SELECT
C.APNT_NO,
A.PT_NAME,
A.PT_NO,
B.MCDP_CD,
B.DR_NAME,
C.APNT_YMD
FROM APPOINTMENT AS C
LEFT JOIN PATIENT AS A ON A.PT_NO = C.PT_NO
LEFT JOIN DOCTOR AS B ON B.DR_ID = C.MDDR_ID
WHERE DATE_FORMAT(C.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND C.APNT_CNCL_YN = 'N' AND B.MCDP_CD='CS'
ORDER BY C.APNT_YMD ASC;

/*
진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시
*/