-- 코드를 입력하세요
SELECT 
    B.USER_ID AS 'USER_ID',
    B.NICKNAME AS 'NICKNAME',
    SUM(A.PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD AS A
LEFT JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;

/*
테이블에서 완료된 중고 거래의 총금액이 70만 원 이상
회원 ID, 닉네임, 총거래금액
총거래금액을 기준으로 오름차순
*/