SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY 
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
ORDER BY ITEM_ID DESC

/*
희귀도가 RARE인 ITEMID를 뽑고, 그 아이템 아이디에 부모 아이디가 있는
각 테이블에서 아이디가 같은 것끼리 join
*/