-- 코드를 입력하세요
SELECT
    A.CATEGORY AS 'CATEGORY',
    SUM(B.SALES) AS 'TOTAL_SALES'
FROM BOOK AS A 
LEFT JOIN BOOK_SALES AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC;

/*
2022년 1월의 카테고리 별 도서 판매량을 합산하고
카테고리(CATEGORY), 총 판매량(TOTAL_SALES)
카테고리명을 기준으로 오름차순 정렬해주세요
*/